version: "3.9"

services:
  app:
    build: .
    container_name: tanstack-start-prod
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      ADDRESS: 0.0.0.0
      # VITE_BASE_URL: ${VITE_BASE_URL}

    restart: unless-stopped
    # networks:
    #  - my-app-network
# networks:
#   my-app-network:
#     driver: bridge
